version: "3.9"
services:

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  api:
    build:
      context: ./backend
    volumes:
     - ./backend/src/migrations:/app/src/migrations
    depends_on:
      - "db"
    links:
      - "db"
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - API_WORKERS=${API_WORKERS}
      - DEBUG=${DEBUG}
      - SQLALCHEMY_DATABASE_DSN=${SQLALCHEMY_DATABASE_DSN}
      - SQLALCHEMY_LOG_ALL=${SQLALCHEMY_LOG_ALL}
    ports:
      - ${API_OUTER_PORT}:${API_PORT}
    entrypoint: [ "/app/scripts/wait-for-it.sh", "db:5432", "--", "/app/scripts/entrypoint.sh", "/app/scripts/run.sh" ]

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - "db"
    ports:
      - ${PGADMIN_OUTER_PORT}:80
